version: '2'
services:
  # database
  db:
    build:
      context: ./database
      args:
        - https_proxy
        - http_proxy
        - no_proxy
    ports:
      - "5532:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - account-net

  # backend server
  express-app:
    build:
      context: .
      args:
        - https_proxy
        - http_proxy
        - no_proxy
    networks:
      - account-net
    depends_on:
      - db
    environment:
      - DB_HOST=db
    ports:
      - "3100:3000"
    entrypoint: ["./bin/wait-for-postgres.sh", "postgres://${DB_USER}@db/${DB_DATABASE}", "npm start"]

  # client app
  client:
    build:
      context: .
      args:
        - https_proxy
        - http_proxy
        - no_proxy
    depends_on:
      - express-app
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=3000
    links:
      - express-app
      - express-app:backend
    networks:
      - account-net
    ports:
      - "8100:8080"
    entrypoint: ["node", "./bin/client"]

volumes:
  pgdata:

networks:
    account-net:
