version: '2'
services:
  # database
  db:
    build:
      context: ./database
      args:
        - https_proxy
        - http_proxy
        - no_proxy
    ports:
      - "5532:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - account-net

  # backend server
  express-app:
    build:
      context: .
      args:
        - https_proxy
        - http_proxy
        - no_proxy
    networks:
      - account-net
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGDATABASE=hpe_account_management
      - PGUSER=hpe_account_management
    ports:
      - "3000:3000"
    entrypoint: ["./bin/wait-for-postgres.sh", "postgres://hpe_account_management@db/hpe_account_management", "npm start"]

  # client app
  client:
    build:
      context: .
      args:
        - https_proxy
        - http_proxy
        - no_proxy
    networks:
      - account-net
    ports:
      - "8080:8080"
    entrypoint: ["node", "./bin/client"]

volumes:
  pgdata:

networks:
    account-net:
