version: '2'
services:
  db:
    build: ./database
    ports:
      - "5532:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  express-app:
    build: .
    entrypoint: ./bin/wait-for-postgres.sh postgres://hpe_account_management@db/hpe_account_management "npm start"
    depends_on:
      - db
    links:
      - db
    environment:
      - PGHOST=db
      - PGDATABASE=hpe_account_management
      - PGUSER=hpe_account_management
    ports:
      - "3100:3000"
  client:
    build: .
    entrypoint: "node ./bin/client"
    ports:
      - "8081:8080"

volumes:
  pgdata:
