FORMAT: 1A

# HPE Account Management API
The HPE Account Management API

# Group Users

Resources related to users

## User Collection [/api/users]

### List All Users [GET]
+ Request
    + Headers

            Authorization: Superuser

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "id": 42,
                "firstName": "Richard",
                "lastName": "Plotkin",
                "isSuperuser": false
            },
            {
                "id": 1010,
                "firstName": "Alexei",
                "lastName": "Ledenev",
                "isSuperuser": false
            }
        ]
        
+ Request
    + Headers

            Authorization: None

+ Response 401 (application/json; charset=utf-8)

            {"message": "Unauthorized"}

### Create a Single User [POST]

+ Request (application/json)

    + Body

            {
                "firstName": "Dummy",
                "lastName": "User",
                "emails": ["dummyuser1@gmail.com", "dummyuser2@gmail.com"]
            }

+ Response 200 (application/json; charset=utf-8)

            {
                "firstName": "Dummy",
                "lastName": "User",
                "id": 1
            }


## User [/api/users/{id}]

A single user.

+ Parameters
    + id: 42 (required, string) - ID of the User

### Retrieve a Single User [GET]

+ Request
    + Headers

            Authorization: Superuser

+ Response 200 (application/json; charset=utf-8)

        {
            "id": 42,
            "firstName": "Richard",
            "lastName": "Plotkin",
            "isSuperuser": false,
            "emails": [
                "richard.plotkin@toptal.com",
                "richardjplotkin@gmail.com"
            ]
        }

+ Request
    + Headers

            Authorization: None

+ Response 401 (application/json; charset=utf-8)

            {"message": "Unauthorized"}


### Update A Single User [PUT]
Note that a user's new emails are inserted, and existing emails will be updated to the user's id.
However, no emails will be removed in this update.

+ Request (application/json)

    + Body

            {
                "firstName": "Richard-Update",
                "lastName": "Plotkin-Update",
                "emails": ["richard@richardplotkin.com"]
            }

+ Response 200 (application/json; charset=utf-8)

            {
                "id": 42,
                "firstName": "Richard-Update",
                "lastName": "Plotkin-Update"
            }

### Delete a Single User [DELETE]
+ Response 200 (application/json; charset=utf-8)

            {"message": "User successfully deleted"}


# Group Accounts
Resources related to accounts

## Account Collection [/api/accounts]
